In [10]:
import string
import pandas as pd
import numpy as np


In [11]:
data = pd.read_csv("datasettokped3.csv", sep=',', encoding='latin1')
data.head(10)

Review SENTIMEN
0        Mudah dan gratisan melimpah. Pokoknya bagus  POSITIF
1  Aplikasinya bagus, dan semua fitur yg ada di d...  POSITIF
2  Tokopedia memang toko online terbaik .jadi mit...  POSITIF
3  Sangat Kecewa karena tidak dapat menyelesaikan...  NEGATIF
4  Aplikasi nya buruk saat kita komplain sulit di...  NEGATIF
5                 Aplikasi susah, ngga bisa komplain  NEGATIF
6  sangat kecewa. sangat sangat kecewa dengan car...  NEGATIF
7                Bagus banget aplikasinya aku suka??  POSITIF
8  Saya sangat suka dengan aplikasi tokopedia san...  POSITIF
9  Sistem Pengiriman buruk dan penanganan komplai...  NEGATIF

In [12]:
# proses case folding 
def casefolding(Review):
    Review = Review.lower()
    return Review
data['Review'] = data['Review'].apply(casefolding)
data.head(10)

Review SENTIMEN
0        mudah dan gratisan melimpah. pokoknya bagus  POSITIF
1  aplikasinya bagus, dan semua fitur yg ada di d...  POSITIF
2  tokopedia memang toko online terbaik .jadi mit...  POSITIF
3  sangat kecewa karena tidak dapat menyelesaikan...  NEGATIF
4  aplikasi nya buruk saat kita komplain sulit di...  NEGATIF
5                 aplikasi susah, ngga bisa komplain  NEGATIF
6  sangat kecewa. sangat sangat kecewa dengan car...  NEGATIF
7                bagus banget aplikasinya aku suka??  POSITIF
8  saya sangat suka dengan aplikasi tokopedia san...  POSITIF
9  sistem pengiriman buruk dan penanganan komplai...  NEGATIF

In [13]:
# proses cleansing remove regex (cleansing) seperti tanda baca dan angka angka
import re
import string
def cleansing(Review):
    Review = Review.strip(" ")
    Review = re.sub(r'[?|$|.|!_:")(-+,]', '', Review)
    Review = re.sub(r'\d+', '', Review)
    Review = re.sub(r"\b[a-zA-Z]\b", "", Review)
    Review = re.sub('\s+',' ', Review)
    return Review
data['Review'] = data['Review'].apply(cleansing)
data.head(10)


Review SENTIMEN
0         mudah dan gratisan melimpah pokoknya bagus  POSITIF
1  aplikasinya bagus dan semua fitur yg ada di dl...  POSITIF
2  tokopedia memang toko online terbaik jadi mitr...  POSITIF
3  sangat kecewa karena tidak dapat menyelesaikan...  NEGATIF
4  aplikasi nya buruk saat kita komplain sulit di...  NEGATIF
5                  aplikasi susah ngga bisa komplain  NEGATIF
6  sangat kecewa sangat sangat kecewa dengan cara...  NEGATIF
7                  bagus banget aplikasinya aku suka  POSITIF
8  saya sangat suka dengan aplikasi tokopedia san...  POSITIF
9  sistem pengiriman buruk dan penanganan komplai...  NEGATIF

In [14]:
from nltk.tokenize import word_tokenize
#NLTK word tokenize
def word_tokenize_wrapper(text):
 return word_tokenize(text)
data['Review'] = data['Review'].apply(word_tokenize_wrapper)
data.head()

Review SENTIMEN
0  [mudah, dan, gratisan, melimpah, pokoknya, bagus]  POSITIF
1  [aplikasinya, bagus, dan, semua, fitur, yg, ad...  POSITIF
2  [tokopedia, memang, toko, online, terbaik, jad...  POSITIF
3  [sangat, kecewa, karena, tidak, dapat, menyele...  NEGATIF
4  [aplikasi, nya, buruk, saat, kita, komplain, s...  NEGATIF

In [15]:
normalizad_word = pd.read_csv("C:/Users/LENOVO/Documents/normalisasi.csv")

normalizad_word_dict = {}

for index, row in normalizad_word.iterrows():
    if row[0] not in normalizad_word_dict:
        normalizad_word_dict[row[0]] = row[1] 

def normalized_term(document):
    return [normalizad_word_dict[term] if term in normalizad_word_dict else term for term in document]

data['Review'] = data['Review'].apply(normalized_term)

data['Review'].head(20)

0     [mudah, dan, gratisan, melimpah, pokoknya, bagus]
1     [aplikasinya, bagus, dan, semua, fitur, yang, ...
2     [tokopedia, memang, toko, online, terbaik, jad...
3     [sangat, kecewa, karena, tidak, dapat, menyele...
4     [aplikasi, nya, buruk, saat, kita, komplain, s...
5              [aplikasi, susah, tidak, bisa, komplain]
6     [sangat, kecewa, sangat, sangat, kecewa, denga...
7               [bagus, banget, aplikasinya, aku, suka]
8     [saya, sangat, suka, dengan, aplikasi, tokoped...
9     [sistem, pengiriman, buruk, dan, penanganan, k...
10    [maaf, kok, tokopedia, nya, tidak, bisa, di, u...
11    [versi, baru, lebih, lemot, tidak, bisa, akses...
12    [kenapa, setelah, di, update, malah, jadi, ero...
13    [tidak, maen, si, karena, semua, produk, ongki...
14              [update, terus, ajabikin, memory, abis]
15    [kenapa, sekarang, tokped, jadi, gini, aplikas...
16         [kelar, instal, tidak, bisa, di, buka, trus]
17                        [ini, gimana, si, eror

In [16]:
# proses filtering
import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords
sw = pd.read_csv("C:/Users/LENOVO/Documents/stopwords.csv")
def stopword_removal(Review):
    filtering = stopwords.words('indonesian','english')
    filtering.extend(sw)
    x = []
    data = []
    def myFunc(x):
        if x in filtering:
            return False
        else:
            return True
    fit = filter(myFunc, Review)
    for x in fit:
        data.append(x)
    return data
data['Review'] = data['Review'].apply(stopword_removal)
data.head(10)

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\LENOVO\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


Review SENTIMEN
0       [mudah, gratisan, melimpah, pokoknya, bagus]  POSITIF
1       [aplikasinya, bagus, fitur, dalamnya, bagus]  POSITIF
2  [tokopedia, toko, online, terbaik, mitra, toko...  POSITIF
3                            [kecewa, menyelesaikan]  NEGATIF
4  [aplikasi, nya, buruk, komplain, sulit, dihubu...  NEGATIF
5                        [aplikasi, susah, komplain]  NEGATIF
6  [kecewa, kecewa, penjual, tokopedia, melayani,...  NEGATIF
7                 [bagus, banget, aplikasinya, suka]  POSITIF
8  [suka, aplikasi, tokopedia, membantu, berbelanja]  POSITIF
9  [sistem, pengiriman, buruk, penanganan, kompla...  NEGATIF

In [17]:
# proses stemming
! pip install Sastrawi
from sklearn.pipeline import Pipeline
from Sastrawi.Stemmer.StemmerFactory import StemmerFactory

def stemming(Review):
    factory = StemmerFactory()
    stemmer = factory.create_stemmer()
    do = []
    for w in Review:
        dt = stemmer.stem(w)
        do.append(dt)
    d_clean=[]
    d_clean=" ".join(do)
    print(d_clean)
    return d_clean
data['Review'] = data['Review'].apply(stemming)

data.to_csv('tokpedstemming.csv', index=False)
data_clean = pd.read_csv('tokpedstemming.csv', encoding='latin1')
data_clean.head()

mudah gratis limpah pokok bagus


You should consider upgrading via the 'c:\users\lenovo\appdata\local\programs\python\python39\python.exe -m pip install --upgrade pip' command.


aplikasi bagus fitur dalam bagus
tokopedia toko online baik mitra toko online nya mudah
kecewa selesai
aplikasi nya buruk komplain sulit hubung
aplikasi susah komplain
kecewa kecewa jual tokopedia layan beli ujung rugi beli
bagus banget aplikasi suka
suka aplikasi tokopedia bantu belanja
sistem kirim buruk tangan komplain buruk
maaf tokopedia nya update ya
versi lot akses flas sale aplikasi mending hapus
update eror quota youtube lancar
maen si produk ongkir langit gratis ongkir gak tu
update ajabikin memory abis
tokped gin aplikasi update bagus hancur bro chat diskusi gak buka data gak hrsnya tahan tingkat pelyanan aplikasi
kelar instal buka trus
gimana si eror mulu
lihat pesan notifikasi coba
jelek kali lihat google barang nya pas download gak barang nya
nih tokopedia fitur tukar hp redmi kasih harga hei otak sih harga nya aja juta harga bekas gak harga hp kepake mending hapus aja deh fitur tukar untulasan lengkap
menu cetak pakai mah
layan buruk lambat nunggu saldo masuk aja hari mi

harga oke sihcuman cod nyaman
kak bayar gimana rumah
dana link aja bom refund chat cs nya balesan
kadang susah beli suruh logout ribet
tokopedia gimana sih promo tranksaksi batal kalo gitu gak promo cashback udah gitu uang gak kembali ovo pdahal ovo sdah aktif bantu gak bales tokopedia
susah bangt ferivikasi foto gagal mulu maap jual toko belah ribet upload foto kali
tolong updatean yaaakarena kesini pusingsaya nyaman tokopedia duludu simpel
aplikasi nya aja keren iklan nya doang bener dah
sengaja isntal gak bisaada dg tokopedia
maaf tokopedia kasih bintang beli barang benuacell tgl beli barang kirim barang kirim tokopediacare bilang balikin dana dana bilang ikhlas in sha allah manfaat salah beli jual benuacell
kecewa sih tokopedia ulas latih prakerja gagal cair insentif ganggu mohon kerja sama bantuanny
enak pakai tokped barang goib alias udah beli bayar dtunggu ujung cancel dah barang udah lbih ganti seller mas gtu
sen bayar anter lapor alamat nyah kesel
baru fiturnya bikin pusing aj

lanja emang bagus sih tp produk nya produk cari ti tokopedia toko belah barang keranjang batas aplikasi toko belah nggak
jarang ongkir gratis kayak marketplace belah
aplikasi bagus tolong fitur banyak
recommended
sip terimakasih tokopedia ikut latih skillacademy moga lancar
terimakasih tokopedia latih jalan lancar
gampang beli latih tokopedia tunggu sertifikat dashboard ya tokopedia
terima kasih tokopedia selesai ikut pelatihanexam jadwal webiner tpi sertifikat jadwal insentif mucul dashboard sayaterimah kasih tokopedia
lumayan oketolong fitur shopee kirim nya atur
beli latih bagus
bantu beli program latih prakerja
kasih bintang dulunanti kalo bagus naikin bintang
aplikasi bantu
aplikasi milik unggul tokopedia harga latih bilang murah
bantu ikut latih prakerja tokopedia sedia lembaga latih lumayan
tau penggunaanya gampangtrima kasih tokopedia
belanja ajar kartu prakerja wawas
terima kasihbagus manfaat
bagus
aplikasi bantu
mudah
aplikasi guna
aplikasi belanja online gratis ongkirnya man

makasih gan moga ringan aplikasi buwat cari rejeki
tokopedia aplikasi
terimakasih tokopedia sedia mudah transaksi prakerja ismunah
terimakasih tokopedia bantu ajar
nice tingkat ya
bagus
top margotop dah
terima kasih tokopedia
alhamdulillah bantu pilih latih diprakerja
tokopedia oke banget
syukur aplikasi manfaat mudah urus beli
suka aplikasi
baik inovasi
aplikasi manfaat tingkat ya
bagus
olshop percaya
suka bantu bangt
manfaat milik kerja
penak gampang mudah simple borong nang tokopedia
bantu
makasih lagi respon sangan cepat beli latih prakerja puas senang mga cepat sertifikat dasboard prakerja
terimakasih tokopedia bantu gampang
terimakasih tokopediasangat muas lembaga latih skill academy baik percaya kualitas
tokohpedia bantu ada latih
bantu
pesan tanggapin kirim enak lasada pesan langsung kirim yes
kineja total aplikasi bagus kecewa kerja admin tokopedia putus kompeten problematika khusus jual
nyesel install tokopedia bikin akun email bocor gara gara tokopedia tolong jaga privasi bk

kecewa dgn pusat resolusi tokopedia admin urus masalah barang customer tanggung penting beli perhati mau mudah aja repot kecewa dgn salah customer tp kurir barang antar kurir sesuai profesionalitas
maaf gak suka loding nya mafaat nya paro
updatenya talu paksa
tokped top up money udah minggu
sih download loginkarena no udah ganti pilih nomor aktif  suruh update download ahh gaje nih tokped
kecewa  ganti nomer telepon hangus suruh kirim data ktp tanggap tolak ktp asli rubah nomer telepon hangus tolak sungguh muas tanggung jawulasan lengkap
tokopedia sen barang udah malam kabar toko chat bilang sampe kecewa mengunakan tokopedia profesional brengsek
kecewa tokped ngebatalin kirim uang tf kembali cek kembali moga depan aman
coba marketplace review tokopedia pakai belanja tokopedia kurang barang marketplace harga beda mahal tokopedia rb ongkos kirim lumayan mahal kirim bal estimasi sd marketplace belah rb rb hr jarak belanja marketplace tokopedia lambat
cashbacknya gimmick transaksi langgar 

terimakasih latih arkademi kartu prakerja
kali pakai aplikasi moga pelamggan setia
mudah cepat
terimakasih
test dlu yak tokped
mantap
murah gratis limpah
terima kasih tokopedia aplikasi tokopedia latih prakerja manfaat
belanja ditempatin nya pisah pisah campur aduk bahu sabun
bagus mantap beli latih
terima kasih tokopedia solusi prakerja
terimakasih aplikasi manfaat bantu
aplikasi tokopedia mudah belanja
puas sm aplikasi inisemoga free ongkir indonesia
cepat praktis cuman biaya dripda toko belah
mantap deh jabar materi gamblang banget
suka sistem nilai jual opsi emoticon harap tambah komentar komentar langgan merupkan poin hitung belanja toko
transaksi nya salah kirim jenis barang sesuai pes jual tokopedia teliti komplain retur lha rugi biaya kirim mesti tokopedia seleksi reseler profesional mending tutup aja akun jual nya
beli pelatiham skill academy selesai pelatahin dr tgl sertifikat msh blm muncul dashbar prakerja gimana sih dri kerja
instal kali ya
update aplikasi update aplikasi 

tokopedia sial beli under batal tokopedia hendak seller otomatis saldo masuk akun tokopedia beli auto verifikasi bayar kapok dah pakai tokopedia
tentu tokped rugi beli untung jual order barang ready stok tp order jual bilang barang kosong kirim barang batal barang komplain barang sesuai selesai beli terima tokopedia lindung maksimal beli dg tokped sempat jual tipu
hitung minggu kirim terima chat toko online aplikasi hubung cs tokopedia balas tolong baik bikin akun gara belanja sepele gin
saldo refund tokopedia cair withdraw opsi sandi pas konfirmasi sandi muncul ingat akun milik sandi solusi cair saldo refund tokopedia
khusus beli harap baca jual upload produk order stock kosong gantungin aja kurir rating toko turun tokopedia pegang dana nya investor gratis lumayan tunggu aja beli sadar reaksi chat pesan bantu parah tindak minta batal nama beli toko aman rating turun enak bukaaan shupii sop nya beli rugi dgn jual profesional
cok aplikasi sampah nggak kaya shoope kalo niat kasih promo g

Review SENTIMEN
0                    mudah gratis limpah pokok bagus  POSITIF
1                   aplikasi bagus fitur dalam bagus  POSITIF
2  tokopedia toko online baik mitra toko online n...  POSITIF
3                                     kecewa selesai  NEGATIF
4           aplikasi nya buruk komplain sulit hubung  NEGATIF

In [2]:
import string
from sklearn.pipeline import Pipeline
import pandas as pd
import numpy as np
import re
data_clean = pd.read_csv('tokpedstemming.csv', encoding='latin1')
data_clean.head()

Review SENTIMEN
0                    mudah gratis limpah pokok bagus  POSITIF
1                   aplikasi bagus fitur dalam bagus  POSITIF
2  tokopedia toko online baik mitra toko online n...  POSITIF
3                                     kecewa selesai  NEGATIF
4           aplikasi nya buruk komplain sulit hubung  NEGATIF

In [3]:
data_clean = data_clean.astype({'SENTIMEN' : 'category'})
data_clean = data_clean.astype({'Review' : 'string'})
data_clean.dtypes

Review        string
SENTIMEN    category
dtype: object

In [4]:
# PROSES TF IDF
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer = CountVectorizer()
X = vectorizer.fit_transform(data_clean['Review'].astype('U'))

tf = TfidfVectorizer()
text_tf = tf.fit_transform(data_clean['Review'].astype('U'))
print(text_tf)

  (0, 130)	0.27610044717306104
  (0, 1430)	0.5571941024068444
  (0, 999)	0.5820878172490146
  (0, 626)	0.4179261664285696
  (0, 1171)	0.3159347523436828
  (1, 375)	0.6210547685583185
  (1, 559)	0.4556309617131673
  (1, 99)	0.24407686181419327
  (1, 130)	0.5891671127161148
  (2, 1258)	0.2027153736411391
  (2, 1148)	0.37354297002342474
  (2, 137)	0.2731328810560897
  (2, 1293)	0.613690125093303
  (2, 1821)	0.5425824561363694
  (2, 1827)	0.1412546022910622
  (2, 1171)	0.23196207041065312
  (3, 1611)	0.7722157351392372
  (3, 842)	0.6353604161445433
  (4, 696)	0.49064111010366385
  (4, 1713)	0.4731476534944883
  (4, 903)	0.42550273658049326
  (4, 295)	0.4731476534944883
  (4, 1258)	0.2781517999508499
  (4, 99)	0.23046234922038208
  (5, 1720)	0.6353729048478102
  :	:
  (918, 690)	0.5488809352311181
  (918, 492)	0.16680062305391016
  (918, 343)	0.17869548495857934
  (918, 287)	0.16401392709366885
  (918, 660)	0.19997875634350235
  (918, 1258)	0.23106749052477651
  (918, 1827)	0.16101071117700

In [5]:
# Import cosine_similarity metrics
from sklearn.metrics.pairwise import cosine_similarity
# compute similarity using cosine similarity
cos_sim=cosine_similarity(text_tf, text_tf)

print(cos_sim)

[[1.         0.1626693  0.07328488 ... 0.         0.         0.        ]
 [0.1626693  1.         0.         ... 0.         0.04672869 0.02494054]
 [0.07328488 0.         1.         ... 0.03476494 0.06958444 0.02500045]
 ...
 [0.         0.         0.03476494 ... 1.         0.0490361  0.        ]
 [0.         0.04672869 0.06958444 ... 0.0490361  1.         0.09074947]
 [0.         0.02494054 0.02500045 ... 0.         0.09074947 1.        ]]


In [60]:
# splitting data 
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(cos_sim, data_clean['SENTIMEN'], test_size=0.2, random_state=33)
print("Jumlah Data Uji:", X_test.shape)
print("Jumlah Data Latih:",X_train.shape)
data_clean['SENTIMEN'].value_counts()
pos = (y_test == 'POSITIF').sum()
neg = (y_test == 'NEGATIF').sum()
postrain = (y_train == 'POSITIF').sum()
negtrain = (y_train == 'NEGATIF').sum()
total = pos + neg
print("Jumlah data uji dengan sentimen positif:", pos)
print("Jumlah data uji dengan sentimen negatif:",neg)
print("Jumlah data latih dengan sentimen positif:", postrain)
print("Jumlah data latih dengan sentimen negatif:",negtrain)
print(total)

Jumlah Data Uji: (184, 920)
Jumlah Data Latih: (736, 920)
Jumlah data uji dengan sentimen positif: 103
Jumlah data uji dengan sentimen negatif: 81
Jumlah data latih dengan sentimen positif: 394
Jumlah data latih dengan sentimen negatif: 342
184


In [62]:
# perform algoritma KNN
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.neighbors import KNeighborsClassifier

clf = KNeighborsClassifier(n_neighbors=3).fit(X_train, y_train)
predicted = clf.predict(X_test)
print(f'confusion matrix:\n {confusion_matrix(y_test, predicted)}')
print('===============================================\n')
tn, fp, fn, tp = confusion_matrix(y_test, predicted).ravel()
print("TN:", tn)
print("FP:", fp)
print("FN:", fn)
print("TP:", tp)
print(classification_report(y_test, predicted, zero_division=0))
print('===============================================\n')
print("Hasil Klasifikasi Sentimen Analisis Tokopedia:")
print("Accuracy:" , accuracy_score(y_test,predicted))
print("Precision:" , precision_score(y_test,predicted, average="binary", pos_label="POSITIF"))
print("Recall:" , recall_score(y_test,predicted, average="binary", pos_label="POSITIF"))
print("f1_score:" , f1_score(y_test,predicted, average="binary", pos_label="POSITIF"))
print("error_rate:", 1-accuracy_score(y_test,predicted))


confusion matrix:
 [[71 10]
 [ 9 94]]

TN: 71
FP: 10
FN: 9
TP: 94
              precision    recall  f1-score   support

     NEGATIF       0.89      0.88      0.88        81
     POSITIF       0.90      0.91      0.91       103

    accuracy                           0.90       184
   macro avg       0.90      0.89      0.90       184
weighted avg       0.90      0.90      0.90       184


Hasil Klasifikasi Sentimen Analisis Tokopedia:
Accuracy: 0.8967391304347826
Precision: 0.9038461538461539
Recall: 0.912621359223301
f1_score: 0.9082125603864736
error_rate: 0.1032608695652174


In [40]:
# splitting data 
import collections, numpy
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(cos_sim, data_clean['SENTIMEN'], test_size=0.3, random_state=33)
print("Jumlah Data Uji:", X_test.shape)
print("Jumlah Data Latih:",X_train.shape)

pos = (y_test == 'POSITIF').sum()
neg = (y_test == 'NEGATIF').sum()
postrain = (y_train == 'POSITIF').sum()
negtrain = (y_train == 'NEGATIF').sum()
total = pos + neg
print("Jumlah data uji dengan sentimen positif:", pos)
print("Jumlah data uji dengan sentimen negatif:",neg)
print("Jumlah data latih dengan sentimen positif:", postrain)
print("Jumlah data latih dengan sentimen negatif:",negtrain)
data_clean['SENTIMEN'].value_counts()

Jumlah Data Uji: (276, 920)
Jumlah Data Latih: (644, 920)
Jumlah data uji dengan sentimen positif: 156
Jumlah data uji dengan sentimen negatif: 120
Jumlah data latih dengan sentimen positif: 341
Jumlah data latih dengan sentimen negatif: 303


POSITIF    497
NEGATIF    423
Name: SENTIMEN, dtype: int64

In [45]:
# perform algoritma 
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.neighbors import KNeighborsClassifier


clf = KNeighborsClassifier(n_neighbors=9).fit(X_train, y_train)
predicted = clf.predict(X_test)

print(f'confusion matrix:\n {confusion_matrix(y_test, predicted)}')
print('===============================================\n')
tn, fp, fn, tp = confusion_matrix(y_test, predicted).ravel()
print("TN:", tn)
print("FP:", fp)
print("FN:", fn)
print("TP:", tp)
print(classification_report(y_test, predicted, zero_division=0))
print('===============================================\n')
print("Hasil Klasifikasi Sentimen Analisis Tokopedia:")
print("Accuracy:" , accuracy_score(y_test,predicted))
print("Precision:" , precision_score(y_test,predicted, average="binary", pos_label="POSITIF"))
print("Recall:" , recall_score(y_test,predicted, average="binary", pos_label="POSITIF"))
print("f1_score:" , f1_score(y_test,predicted, average="binary", pos_label="POSITIF"))
print("error_rate:", 1-accuracy_score(y_test,predicted))


confusion matrix:
 [[107  13]
 [ 33 123]]

TN: 107
FP: 13
FN: 33
TP: 123
              precision    recall  f1-score   support

     NEGATIF       0.76      0.89      0.82       120
     POSITIF       0.90      0.79      0.84       156

    accuracy                           0.83       276
   macro avg       0.83      0.84      0.83       276
weighted avg       0.84      0.83      0.83       276


Hasil Klasifikasi Sentimen Analisis Tokopedia:
Accuracy: 0.8333333333333334
Precision: 0.9044117647058824
Recall: 0.7884615384615384
f1_score: 0.8424657534246576
error_rate: 0.16666666666666663


In [33]:
# splitting data 
import collections, numpy
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(cos_sim, data_clean['SENTIMEN'], test_size=0.4, random_state=33)
print("Jumlah Data Uji:", X_test.shape)
print("Jumlah Data Latih:",X_train.shape)
data_clean['SENTIMEN'].value_counts()
print("Jumlah data uji dengan sentimen positif:", (y_test == 'POSITIF').sum())
print("Jumlah data uji dengan sentimen negatif:",(y_test == 'NEGATIF').sum())
print("Jumlah data latih dengan sentimen positif:", (y_train == 'POSITIF').sum())
print("Jumlah data latih dengan sentimen negatif:",(y_train == 'NEGATIF').sum())

Jumlah Data Uji: (368, 920)
Jumlah Data Latih: (552, 920)
Jumlah data uji dengan sentimen positif: 202
Jumlah data uji dengan sentimen negatif: 166
Jumlah data latih dengan sentimen positif: 295
Jumlah data latih dengan sentimen negatif: 257


In [38]:
# perform algoritma 
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.neighbors import KNeighborsClassifier


clf = KNeighborsClassifier(n_neighbors=9).fit(X_train, y_train)
predicted = clf.predict(X_test)

print(f'confusion matrix:\n {confusion_matrix(y_test, predicted)}')
print('===============================================\n')
tn, fp, fn, tp = confusion_matrix(y_test, predicted).ravel()
print("TN:", tn)
print("FP:", fp)
print("FN:", fn)
print("TP:", tp)
print(classification_report(y_test, predicted, zero_division=0))
print('===============================================\n')
print("Hasil Klasifikasi Sentimen Analisis Tokopedia:")
print("Accuracy:" , accuracy_score(y_test,predicted))
print("Precision:" , precision_score(y_test,predicted, average="binary", pos_label="POSITIF"))
print("Recall:" , recall_score(y_test,predicted, average="binary", pos_label="POSITIF"))
print("f1_score:" , f1_score(y_test,predicted, average="binary", pos_label="POSITIF"))
print("error_rate:", 1-accuracy_score(y_test,predicted))


confusion matrix:
 [[146  20]
 [ 39 163]]

TN: 146
FP: 20
FN: 39
TP: 163
              precision    recall  f1-score   support

     NEGATIF       0.79      0.88      0.83       166
     POSITIF       0.89      0.81      0.85       202

    accuracy                           0.84       368
   macro avg       0.84      0.84      0.84       368
weighted avg       0.84      0.84      0.84       368


Hasil Klasifikasi Sentimen Analisis Tokopedia:
Accuracy: 0.8396739130434783
Precision: 0.8907103825136612
Recall: 0.806930693069307
f1_score: 0.8467532467532467
error_rate: 0.16032608695652173


In [116]:
from sklearn.model_selection import cross_val_score
from sklearn.neighbors import KNeighborsClassifier

In [123]:
knn = KNeighborsClassifier(n_neighbors=3)
cross_val_score(knn, cos_sim, data_clean['SENTIMEN'], cv=10)

array([0.81521739, 0.83695652, 0.7826087 , 0.88043478, 0.86956522,
       0.84782609, 0.80434783, 0.84782609, 0.90217391, 0.82608696])

In [124]:
cross_val_score(knn, cos_sim, data_clean['SENTIMEN'], cv=10).mean()

0.8413043478260869

In [128]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier 
from sklearn.tree import DecisionTreeClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.linear_model import LogisticRegression
model = LogisticRegression()

In [126]:
dataclean = pd.read_csv('tokpeduji.csv', encoding='latin1')
dataclean.head()

Review
0  alhamdulillah senang dgn aplikasi pesan barang...
1  tokopedia ditinggalin ya lot banget buka aplikasi

In [127]:
dataclean = dataclean.astype({'Review' : 'string'})
dataclean.dtypes

Review    string
dtype: object

In [128]:
# PROSES TF IDF
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer1 = CountVectorizer()
B = vectorizer.fit_transform(dataclean['Review'].astype('U'))

tf1 = TfidfVectorizer()
texttf = tf.fit_transform(dataclean['Review'].astype('U'))
print(texttf)

  (0, 23)	0.14989582193179826
  (0, 17)	0.14989582193179826
  (0, 18)	0.14989582193179826
  (0, 0)	0.14989582193179826
  (0, 13)	0.14989582193179826
  (0, 6)	0.2997916438635965
  (0, 7)	0.14989582193179826
  (0, 10)	0.2997916438635965
  (0, 21)	0.44968746579539476
  (0, 16)	0.14989582193179826
  (0, 8)	0.14989582193179826
  (0, 22)	0.14989582193179826
  (0, 20)	0.14989582193179826
  (0, 3)	0.14989582193179826
  (0, 5)	0.2997916438635965
  (0, 15)	0.14989582193179826
  (0, 2)	0.10665211186463855
  (0, 11)	0.44968746579539476
  (0, 19)	0.14989582193179826
  (0, 1)	0.14989582193179826
  (1, 9)	0.3920440146223274
  (1, 4)	0.3920440146223274
  (1, 14)	0.3920440146223274
  (1, 25)	0.3920440146223274
  (1, 12)	0.3920440146223274
  (1, 24)	0.3920440146223274
  (1, 2)	0.2789425453258252


In [131]:
# Import cosine_similarity metrics
from sklearn.metrics.pairwise import cosine_similarity
# compute similarity using cosine similarity
cos_sim=cosine_similarity(texttf)

print(cos_sim)

[[1.         0.02974981]
 [0.02974981 1.        ]]


In [142]:
def preprocess_data(data):
    #cleanseing
    data = casefolding(data)
    data = cleansing(data)
     data = word_tokenize_wrapper(data)
    data = stopword_removal(databaru)
    databaru = stemming data(databaru)
    databaru = tf.fit_transform(databaru)
    
    return databaru

IndentationError: unexpected indent (<ipython-input-142-1b081593e87c>, line 5)

In [64]:
import matplotlib.pyplot as plt
from wordcloud import WordCloud, ImageColorGenerator

In [65]:
from wordcloud import WordCloud

import matplotlib.pyplot as plt

In [66]:
wordcloud = WordCloud(width=1600, height=800, max_font_size=200, background_color='white')

In [71]:
wordcloud.generate(tokpedstemming.csv)

NameError: name 'tokpedstemming' is not defined